project:
  type: website

website:
  title: "DiLab Site"
  navbar:
    left:
      - text: "Home"
        href: index.md
      - text: "News"
        href: news.md
      - text: "People"
        href: people.md
      - text: "Publications"
        href: publications.md

# where the rendered site will be written (for GitHub Pages use `docs`)
output-dir: docs

# treat files under _posts as a posts collection (optional)
collections:
  posts:
    type: posts
    sort: date
