project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll
  render:
    - index.md
    - news.md
    - people.md
    - publications.md
    - pi.md
    - contact.md

website:
  title: "Zhao Lab"
  navbar:
    left:
      - text: "News"
        href: news.md
      - text: "PI"
        href: pi.md
      - text: "People"
        href: people.md
      - text: "Publications"
        href: publications.md
      - text: "Contact"
        href: contact.md
    # Temporarily hide Chinese switch while zh site is under construction
    # right: []

collections:
  posts:
    type: posts
    sort: date

format:
  html:
    css: styles.css
    include-in-header: _includes/head.html
    anchor-sections: false
